#Bai thuc hanh 

In [ ]:
#Bai 1
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
print(b)
c = np.array([[(0.5, 1.5, 10), (3,2,1)],[(6,5,4), (7,8,9)]])
print(c)
A = np.matrix(np.random.random((2,2)))
print(A)
B = np.asmatrix(b)
print(B)
C = np.matrix(np.random.random((10,5)))
print(C)
D = np.matrix([[4, 3], [2, 6]])
print(D)
F = np.eye(3, k=1)
print(F)
F1 = np.eye(3, k=0)
print(F1)
F2 = np.eye(3, k=-1)
print(F2)

[1 2 3]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]
[[0.06431989 0.79351307]
 [0.86737041 0.97253905]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.60591814 0.81906582 0.3043514  0.11219464 0.83737702]
 [0.13085145 0.72262583 0.89944635 0.25655493 0.86399707]
 [0.04452376 0.66979391 0.37806509 0.05781912 0.84760822]
 [0.94486073 0.25455138 0.14049912 0.62008666 0.28619648]
 [0.12983942 0.18366115 0.7255365  0.74263391 0.02048635]
 [0.03523158 0.42154264 0.96379619 0.18769034 0.34576263]
 [0.83112417 0.0143808  0.02346258 0.4687112  0.63773792]
 [0.33632694 0.57843903 0.70299641 0.89708856 0.69877496]
 [0.79131985 0.43001334 0.91042631 0.37039364 0.49662955]
 [0.4592744  0.63673373 0.90249172 0.72755356 0.51744623]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [10]:
#Xu ly don gian
from scipy import linalg
import numpy as np
A = np.matrix(np.random.random((2,2)))
print(A)
F3 = np.linalg.matrix_rank(C)
print(F3)
F4 = A.I
print(F4)
F5 = linalg.inv(A)
print(F5)
F6 = linalg.det(A)
print(F6)
F7 = A.T
print(F7)
F8 = A.H
print(F8)


[[0.68856715 0.73264183]
 [0.43447737 0.2366873 ]]
5
[[-1.52366086  4.71633955]
 [ 2.79692306 -4.43261137]]
[[-1.52366086  4.71633955]
 [ 2.79692306 -4.43261137]]
-0.15534119596298201
[[0.68856715 0.43447737]
 [0.73264183 0.2366873 ]]
[[0.68856715 0.43447737]
 [0.73264183 0.2366873 ]]


In [11]:
#Phuong trinh toan tinh
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
print(b)
A = np.matrix(np.random.random((2,2)))
print(A)
F = np.eye(3, k=1)
print(F)
F9 = linalg.solve(A, b)
print(F9)
E = np.matrix(a).T
print(E)
E1 = linalg.lstsq(F, E)
print(E1)

[1 2 3]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.30351773 0.86490532]
 [0.45394513 0.6739332 ]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[-3.58343803-13.85544177j  0.        +15.82749955j
   0.        +16.84293664j]
 [ 2.41371735+15.26799746j  0.         -3.24188868j
   0.         -2.442036j  ]]
[[1]
 [2]
 [3]]
(array([[0.],
       [1.],
       [2.]]), array([], dtype=float64), 2, array([1., 1., 0.]))


In [14]:
#Cac ham ma tran
from scipy import linalg
import numpy as np
A = np.matrix(np.random.random((2,2)))
print(A)
D = np.matrix([[4, 3], [2, 6]])
print(D)
H1 = np.add(A, D)
print(H1)
H2 = np.subtract(A, D)
print(H2)
H3 = np.divide(A, D)
print(H3)
H4 = A @ D 
H4 = np.multiply(D, A)
H4 = np.dot(A, D)
H4 = np.vdot(A, D)
print(H4)
H5 = linalg.expm(A)
print(H5)
H6 = linalg.logm(A)
print(H6)


[[0.91337688 0.73481931]
 [0.0402339  0.68887073]]
[[4 3]
 [2 6]]
[[4.91337688 3.73481931]
 [2.0402339  6.68887073]]
[[-3.08662312 -2.26518069]
 [-1.9597661  -5.31112927]]
[[0.22834422 0.24493977]
 [0.02011695 0.11481179]]
[[3.65350752]]
[[2.52704793 1.64873919]
 [0.09027419 2.0233158 ]]
[[-0.11240294  0.9381537 ]
 [ 0.05136717 -0.39903297]]


In [15]:
#Bai 2
import numpy as np
#Ma tran A
A = np.array([[0,1],[1,0]])
print(A)
temp = A.dot(A)
print(temp)
k = 6 
for i in range(k-1):
    temp = temp.dot(A)
    print(temp)
    print('---')
#Ma tran B
B = np.array([ [0,-1], [-1,0]])
print(B)
temp = B.dot(B)
print(temp)
k = 5
for i in range(k-1):
    temp = temp.dot(B)
    print(temp)
    print('---')
    

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


In [16]:
#Ma tran hoi tu
import numpy as np
C = np.array([[1, 0, 0], [0, 0.5, 1], [0, 0, 0.5]])
print(C)
temp = C.dot(C) 
print(temp)
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp)
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp)


[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
#Bai 3
import numpy as np
M = np.array([[0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) 
print (MM)
MM = M.dot(M)
print(MM)
for i in range(100):
    MM = MM.dot(M)
print(MM)

[[0.7  0.45]
 [0.3  0.55]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.6 0.6]
 [0.4 0.4]]


In [18]:
#Bai 3
import numpy as np
M = np.array([[0.5, 0.5], [0.5, 0.5]])
MM = M.dot(M) 
print (MM)
MM = M.dot(M)
print(MM)
for i in range(100):
    MM = MM.dot(M)
print(MM)

[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]


In [19]:
#Bai 4
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) 
print (P)

print (L)

print (U)
U1 = L.dot(U)
print(U1)


[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]
[[0.8 0.3]
 [0.2 0.7]]


In [1]:
#Toan Ung Dung 1
import numpy as np
A = np.array([
    [1, -2, 2],
    [-1, 1, 3],
    [1, -1, -4]
])
vectors = {
    "O.C": np.array([17, 34, 5]),
    "_DU": np.array([0, 6, 26]),
    "~L": np.array([33, 0, 14]),
    "Ê.": np.array([12, 9, 34]),
    "UU": np.array([25, 35, 35])
}
for label, vec in vectors.items():
    result = vec @ A
    print(f"Kết quả {label}: {result}")



Kết quả O.C: [-12  -5 116]
Kết quả _DU: [ 20 -20 -86]
Kết quả ~L: [ 47 -80  10]
Kết quả Ê.: [ 37 -49 -85]
Kết quả UU: [ 25 -50  15]


In [2]:
#Toan Ung Dung 2
import numpy as np
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [1, 1, 0, 0]
])
temp = A.dot(A)
print("A^2:")
print(temp)
print()
# Tính A^3
temp = temp.dot(A)
print("A^3:")
print(temp)
print()

sumA = A.copy()
temp = A.copy()
k = 3  
for i in range(1, k):
    temp = temp.dot(A)
    sumA = sumA + temp
print("A + A^2 + A^3:", sumA)



A^2:
[[1 1 1 0]
 [0 0 1 1]
 [1 1 1 1]
 [0 1 1 1]]

A^3:
[[0 1 2 2]
 [1 1 1 1]
 [1 2 2 2]
 [1 1 2 1]]

A + A^2 + A^3: [[1 3 3 3]
 [1 1 3 2]
 [2 3 4 4]
 [2 3 3 2]]


In [3]:
#Bai tap 1
import numpy as np
#a
A = np.array([
    [2, 1, 3],
    [1, 1, 1],
    [1, -1, 2]
])
det = np.linalg.det(A)
print("Định thức của A:", det)
if det == 0:
    print("Ma trận không khả nghịch.")
else:
    print("Ma trận khả nghịch. Ma trận nghịch đảo là:")
    A_inv = np.linalg.inv(A)
    print(A_inv)
#b
text = input("Nhập họ tên hoặc mã số sinh viên: ")
#c
while len(text) % 3 != 0:
    text += ' '  
ascii_vals = [ord(c) for c in text]
matrix_text = np.array(ascii_vals).reshape(-1, 3).T  
encoded = A.dot(matrix_text)
print("Mã hóa (ma trận):")
print(encoded)
#d
decoded_matrix = A_inv.dot(encoded).round().astype(int)
decoded_chars = [chr(i) for i in decoded_matrix.T.flatten()]
decoded_text = ''.join(decoded_chars).strip()
print("Giải mã được chuỗi:")
print(decoded_text)


Định thức của A: -1.0
Ma trận khả nghịch. Ma trận nghịch đảo là:
[[-3.  5.  2.]
 [ 1. -1. -1.]
 [ 2. -3. -1.]]
Mã hóa (ma trận):
[[679]
 [343]
 [219]]
Giải mã được chuỗi:
tun


In [4]:
#Bai tap 2
import numpy as np
def continued_fraction(c):
    """
    Tính phân số p_n / q_n từ dãy liên phân số [c0, c1, ..., cn]
    """
    n = len(c)
    M = np.array([[1, 0], [0, 1]])
    for ci in c:
        Mi = np.array([[ci, 1], [1, 0]])
        M = np.dot(M, Mi)

    pn = M[0][0]
    qn = M[1][0]
    return pn, qn
coeffs = [3, 1, 2]
pn, qn = continued_fraction(coeffs)
print(f"Chuỗi hệ số: {coeffs}")
print(f"Phân số tương ứng: {pn}/{qn} = {pn/qn}")


Chuỗi hệ số: [3, 1, 2]
Phân số tương ứng: 11/3 = 3.6666666666666665
