#Bai Thuc Hanh

In [2]:
#1
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print(tich)
dot = np.dot(a,b)
print(dot)

32
32


In [3]:
#2
import numpy as np
a = np.array([1,2,-3])
KQ = np.linalg.norm(a)
print(KQ)
b = np.array([1,2,-3])
kq = np.linalg.norm(b,1)
print(kq)

3.7416573867739413
6.0


In [6]:
#3
import math 
import numpy as np
def chuan(a, p):
    a = np.array(a)
    return np.sum(np.abs(a)**p)**(1/p)
a = np.array([1,2,-3])
KQ = chuan(a,1)
print(KQ)
KQ1 = np.linalg.norm(a,1)
print(KQ1)
KQ2 = chuan(a,2)
print(KQ2)
KQ3 = np.linalg.norm(a,2)
print(KQ3)
KQ4 = chuan(a,3)
print(KQ4)
KQ5 = np.linalg.norm(a,3)
print(KQ5)
KQ6 = chuan(a, 1000)
print(KQ6)
KQ7 = np.linalg.norm(a,1000)
print(KQ7)
#4
from scipy import linalg
KQ8 = linalg.norm(a)
print(KQ8) 
KQ9 = linalg.norm(a, 100)
print(KQ9)
KQ10 = linalg.norm(a, 1000)
print(KQ10)




6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
1.0442214818467515
inf


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/numpy/linalg/_linalg.py:2788: RuntimeWarning: overflow encountered in power
  absx **= ord


3.7416573867739413
3.0
inf


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/numpy/linalg/_linalg.py:2788: RuntimeWarning: overflow encountered in power
  absx **= ord


In [7]:
#5
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)
v = (1.0/m)*MT.dot(mi)
print(v)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[1.3 0.9 0. ]


In [8]:
#6
import numpy as np
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
v0 = np.array([0.95, 0.05])
A_100 = np.linalg.matrix_power(A, 100)
v100 = np.dot(A_100, v0)
print("x100 =", v100[0])
print("y100 =", v100[1])


x100 = 0.9855072337572738
y100 = 0.014492766242729948


In [9]:
#7
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])
A = sym.Matrix([[1, -68],
                [1,  1]])
v = sym.Matrix([0, 1])

nghiem = sym.solve([A * xy - v], (x, y))
print("\nGiải bằng sympy:")
print(sym.pretty(nghiem))



Giải bằng sympy:
⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [10]:
#8
import numpy as np
A = np.array([[1, 6],
              [5, 2]])
u = np.array([6, -5])
Au = np.dot(A, u)
lambda_u = -4 * u
print("A @ u =", Au)
print("-4 * u =", lambda_u)
print("Au == -4u ?", np.allclose(Au, lambda_u))


A @ u = [-24  20]
-4 * u = [-24  20]
Au == -4u ? True


In [11]:
#9
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])
print (sympy.pretty(nghiem))



[-7.000, 3.000]
[-7, 3]


In [12]:
#10
import numpy as np
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) 
print (P1)
KQ = A.dot(P)
print(KQ)
KQ1 = P.dot(D)
print(KQ1)
KQ2 = P @ (D ** 1000) @ P1
print(KQ2)
print (D **2)


[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
[[49  0]
 [ 0  9]]


#Bai Tap Chuong

In [15]:
#BT1
import numpy as np
import math
a = np.array([1, 2, 3])
mag_a = np.sqrt(a.dot(a))
print("Cách a - np.sqrt(a.dot(a)) =", mag_a)
mag_b = np.sqrt(a @ a)
print("Cách b - np.sqrt(a @ a) =", mag_b)
mag_c = np.sqrt(np.inner(a, a))
print("Cách c - np.sqrt(np.inner(a,a)) =", mag_c)
mag_d_func = lambda x: math.sqrt(sum(i**2 for i in x))
mag_d = mag_d_func(a)
print("Cách d - lambda x, sqrt(sum(i**2)) =", mag_d)


Cách a - np.sqrt(a.dot(a)) = 3.7416573867739413
Cách b - np.sqrt(a @ a) = 3.7416573867739413
Cách c - np.sqrt(np.inner(a,a)) = 3.7416573867739413
Cách d - lambda x, sqrt(sum(i**2)) = 3.7416573867739413


In [13]:
#BT2
import numpy as np
from numpy.linalg import norm
from math import acos, degrees
def nhap_vector():
    u = np.array([float(x) for x in input("Nhập vector u (cách nhau bởi dấu cách): ").split()])
    v = np.array([float(x) for x in input("Nhập vector v (cách nhau bởi dấu cách): ").split()])
    return u, v1
# a. Tính khoảng cách giữa 2 vector
def tinh_khoang_cach(u, v):
    return norm(u - v)
# b. Tính góc giữa 2 vector (kết quả trả về đơn vị độ)
def tinh_goc(u, v):
    dot_uv = np.dot(u, v)
    cos_theta = dot_uv / (norm(u) * norm(v))
    cos_theta = np.clip(cos_theta, -1, 1)
    return degrees(acos(cos_theta))
# c. Tính phép chiếu trực giao p
def phep_chieu(u, v):
    dot_uv = np.dot(u, v)
    dot_vv = np.dot(v, v)
    return (dot_uv / dot_vv) * v
u, v = nhap_vector()
kc = tinh_khoang_cach(u, v)
print("a) Khoảng cách ||u - v|| =", kc)
goc = tinh_goc(u, v)
print("b) Góc giữa u và v (độ) =", goc)
p = phep_chieu(u, v)
print("c) Phép chiếu trực giao p = ", p)


a) Khoảng cách ||u - v|| = 2.8284271247461903
b) Góc giữa u và v (độ) = 10.304846468766044
c) Phép chiếu trực giao p =  [1.32 1.76]
