#Bai thuc hanh

In [1]:
#Bai 1
danhsach1 = [1.,3.]
danhsach2 = [5.,7.]
danhsach = danhsach1 + danhsach2
print(danhsach)
danhsachgapdoi = 2*danhsach
print(danhsachgapdoi)
danhsachchiadoi = danhsach/2
print(danhsachchiadoi)
#2
monhoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thutu = [2, 3, 4, 1]
diemso = [10, 9, 8, 7]
anhxa = zip(thutu, monhoc, diemso)
print(anhxa)
taphop = set(anhxa) 
print(taphop)
lay_TT, lay_monhoc , lay_diem = zip(*anhxa)
lay_monhoc
#3
import itertools
tapsinh = list(itertools.chain(range(4), range(5,10), range(15,20)))
print(tapsinh)
#5
list(zip(range(4), range(7, 12), reversed(range(11))))

[1.0, 3.0, 5.0, 7.0]
[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [2]:
#Bai 2
#V1
from sympy import Symbol
x = Symbol('x')
f = x + x + x + 2
print(f)
#V2
a = Symbol('Noi')
b = Symbol('Chim')
c = 3*b + 7*a
print(c)
a.name
print(a.name)
b.name 
print(b.name)
#V3
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
s = x*y + y*x
print(s)
p = x*(x+2*x)
print(p)
g = (x+2)*(y+3)
print(g)
h = (x+2)*(y+3) + (x+2)*(x-3)
print(h)
j = x*(-x +2*x-x)
print(j)
k = (x+2)*(y+3)
k.expand()

3*x + 2
3*Chim + 7*Noi
Noi
Chim
2*x*y
3*x**2
(x + 2)*(y + 3)
(x - 3)*(x + 2) + (x + 2)*(y + 3)
0


x*y + 3*x + 2*y + 6

In [4]:
#Bai 3
#V1
from sympy import factor, Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x**3 - y**3
print(factor(bieuthuc))
#V2
from sympy import expand, Symbol
x = Symbol('x')
y = Symbol('y')
bieu_thuc = (x-y)*(x**2 + x*y + y**2)
print(expand(bieu_thuc))

(x - y)*(x**2 + x*y + y**2)
x**3 - y**3


In [3]:
#Bai 4
#V1
from sympy import pprint, Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - 2*x*y + y**2 
pprint(bieuthuc)
#V2
from sympy import pprint, Symbol, factor
from sympy import init_printing
init_printing(order='rev-lex')
bieu_thuc = x*x - 2*x*y + y**2
pprint(bieu_thuc)
bieu_thuc1 = factor(bieu_thuc)
pprint(bieu_thuc1)

 2            2
x  - 2⋅x⋅y + y 
 2            2
y  - 2⋅x⋅y + x 
        2
(-y + x) 


In [ ]:
#Bai 5
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x -x*y - y*y
print(bieuthuc)
giatri = bieuthuc.subs({x:3, y:2})
print(giatri)
print(x)
print(y)

In [5]:
#Bai 6
import numpy as np 
from numpy import *
vec1 = np.array([1., 3., 5.])
c = vec1 * 2
print(c)
d = vec1 * vec1
print(d)
e = vec1 / 2
print(e)
f = vec1 + vec1
print(f)
vec2 = array([2., 4.])
g = vec1 + vec2
print(g)
vec3 = array([2., 4., 6.])
h = vec1 + vec3
print(h)
j = vec1 / vec3 
print(j)
k = vec1 * vec3
print(k)
l = 2*vec1 + 5*vec3
print(l)
n = vec3[2]
print(n)
vec4 = np.linspace(0, 20, 5)
print(vec4)
vec5 = np.zeros(5)
print(vec5)
vec6 = np.ones(5)
print(vec6)
vec7 = np.empty(5)
print(vec7)
vec8 = np.random.random(5)
print(vec8)
v = np.array([1.,3.,5.])
v1 = np.sum(v)
print(v1)
v2 = v.shape 
print(v2)
v3 = v.transpose()
print(v3)
v4 = v[:2]
print(v4)
v[0] = 5 
print(v)
v4[:2] = [1.,2.,3.]
print(v4)

[ 2.  6. 10.]
[ 1.  9. 25.]
[0.5 1.5 2.5]
[ 2.  6. 10.]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
#Bai 7
#T1
from sympy import Symbol
x = Symbol('x')
y = Symbol('')
bieuthuc = x**2 - 3*x + 9
giatri = bieuthuc.subs({x: 3, y: x})
print(giatri)
#T2 
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x**2 - 3*x + 9
giatri = bieuthuc.subs({x: y, y: 3})
print(giatri) 
#T3
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x**2 - 3*x + 9
giatri = bieuthuc.subs({y: x}).subs({x: 3})
print(giatri)
#T4
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
print(bieuthuc)
bieuthuc_moi = bieuthuc.subs({x:1-y}) 
print(bieuthuc_moi)
from sympy import simplify
dongian = simplify(bieuthuc_moi)
print(dongian)
#T5
from sympy import Symbol
from sympy import sin, cos
x = Symbol('x')
y = Symbol('y')
bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
print(bt_moi)

#Bai tap chuong

In [ ]:
#Bai 1
from sympy import Symbol, solve
#1
x = Symbol('x')
bieuthuc = x + 3 - 5
nghiem = solve(bieuthuc)
print("Nghiệm của phương trình x + 3 - 5 = 0 là:", nghiem)
#2
bieuthuc = x**2 + 3 - 5  
nghiemx = solve(bieuthuc)
print("Nghiệm của phương trình x^2 + 3 - 5 = 0 là:", nghiemx)
print("Nghiệm thứ nhất:", nghiemx[0])
print("Nghiệm thứ hai:", nghiemx[1])

In [ ]:
#Bai 2
from sympy import Symbol, solve
#1
x = Symbol('x')
ptb2 = x**2 + 9*x + 8
nghiem = solve(ptb2, dict=True)
print("Nghiệm của phương trình là:", nghiem)
#2
ptb2 = x**2 + x + 10
nghiemx = solve(ptb2, dict=True)
print("Nghiệm của x là:", nghiemx)

In [ ]:
#Bai 3
from sympy import Symbol, solve
x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
ptb2 = a * x**2 + b * x + c
nghiem = solve(ptb2, x, dict=True)
print("Nghiệm tổng quát của phương trình là:", nghiem)

In [ ]:
#Bai 4
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
pt1 = 2*x + 3*y - 12
pt2 = 3*x - 2*y - 5
nghiem = solve((pt1, pt2), dict=True)
print("Nghiệm của hệ phương trình là:",nghiem)
nghiem = nghiem[0]
print("Kiểm tra pt1 với nghiệm vừa tìm:", pt1.subs({x: nghiem[x], y: nghiem[y]}))
print("Kiểm tra pt2 với nghiệm vừa tìm:", pt2.subs({x: nghiem[x], y: nghiem[y]}))

In [6]:
#Bai 5
import numpy as np
M1 = np.array([[9, 12], [23, 30]])
print("Ma trận M1:", M1)
u = np.array([2, 1])
print("Vector u:", u)
tichM1u = M1.dot(u)
print("Kết quả M1.dot(u):", tichM1u)
tichuM1 = u.dot(M1)
print("Kết quả u.dot(M1):", tichuM1)
print("Kết quả np.dot(M1, u):", np.dot(M1, u))
print("\nKết quả np.dot(u, M1):", np.dot(u, M1))
#2 Các lệnh
mat1 = np.zeros([5,5])
print(mat1)
mat2 = np.ones( [5,5])
print(mat2)
mat3 = mat1 + 2* mat2
print(mat3)
mat4 = mat3
mat3[3][2] = 10
print(mat4)
mat5 = np.copy(mat3)
mat3[3][2] = 10
print(mat5)
mat6 = np.empty([4, 5])
print(mat6)
mat7 = np.identity(4)
print(mat7)
mat8 = np.random.random([4,5])
print(mat8)

Ma trận M1: [[ 9 12]
 [23 30]]
Vector u: [2 1]
Kết quả M1.dot(u): [30 76]
Kết quả u.dot(M1): [41 54]
Kết quả np.dot(M1, u): [30 76]

Kết quả np.dot(u, M1): [41 54]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.0956154  0.00171092 0.92108125 0.27273043 0.9980311 ]
 [0.46886654 0.86935662 0.0088792  0.82018015 0.43542385]
 [0.1107268  0.4152668  0.92218844 0.63650895 0.95321012]
 [0.44697991 0.27186639