#Bai Thuc Hanh

In [ ]:
#Bai1
def scale(a, v):
    return [a*vi for vi in v]
v = [3, 5, 7]
print(scale(10, v))
#2
def sumvector(v, w):
    return [vi+wi for (vi, wi) in zip(v, w)]
v = [3, 5, 7]
w = [2, 4, 6]
print(sumvector(v, w))
#3
def dotvector(v, w):
    return sum([vi*wi for (vi, wi) in zip(v, w)])
print(dotvector(v, w))
#4
def lenvector(v):
    return dotvector(v, v)
print(lenvector(w))

In [ ]:
#Bai 2 
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print("Mảng scores:", scores)
print("scores >= 0:", (scores >= 0))
print("scores < 0:", (scores < 0))
result_2_classes = np.select(
    [scores >= 0, scores < 0],
    np.array(['so duong', 'so am'], dtype=object)
)
print("Phân loại 2 loại:", result_2_classes)
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print("Mảng scores mới:", scores)
result_3_classes = np.select(
    [scores > 0, scores == 0, scores < 0],
    np.array(['so duong', 'so 0', 'so am'], dtype=object)
)
print("Phân loại 3 loại:", result_3_classes)

In [ ]:
#Bai 3
#1
import numpy as np #Lệnh để nạp thư viện numpy vào bộ nhớ để xử lý.
from scipy import linalg, sparse #Tải 2 thư viện linalg và sparse của scipy vào bộ nhớ để sử dụng.
#2
D = np.array([[3,4],[5,6]]) #Tạo ma trận từ danh sách
print(D)
#3
C = np.array(np.random.random((5, 7))) #Ma trận ngẫu nhiên 5x7
print(C)
#4
A = np.array(np.random.random((2, 2))) #Ma trận ngẫu nhiên 2x2
print(A)
#5
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)]) #Chuyển array thành matrix
B = np.asmatrix(b)
print(b)
print(B)
#6
A.T 
print(A.T)
#7
#8
linalg.inv(A)
M = np.array([[-1, 3, 2],[0, -2, 1],[1, 5, -2]])
M_lower = np.tril(M)
print(M_lower)
#9
M = np.array([[-1, 3, 2],[0, -2, 1],[1, 5, -2]])
M_upper = np.triu(M)
print(M_upper)
#10
M = np.array([[-1, 3, 2],[0, -2, 1],[1, 5, -2]])
v_diag = np.diag(M) # vector duong cheo
print(v_diag)
M_diag = np.diag(v_diag)
print(M_diag)

[[3 4]
 [5 6]]
[[0.62674929 0.31393015 0.14519642 0.39771372 0.19773783 0.29380521
  0.84012895]
 [0.54495471 0.33771046 0.30992883 0.81083973 0.28798059 0.53537333
  0.51351629]
 [0.92000344 0.08202527 0.94742148 0.07538687 0.0922387  0.5639453
  0.51736686]
 [0.67484164 0.58310687 0.33636179 0.07540802 0.59543144 0.37086755
  0.77177502]
 [0.73867321 0.52118651 0.07422104 0.27306473 0.19449803 0.8016914
  0.65026744]]
[[0.98645445 0.42652629]
 [0.02096482 0.63424553]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[0.98645445 0.02096482]
 [0.42652629 0.63424553]]
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [ ]:
#Bai 4 
import sympy as sp 
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
a = sp.solve([x*x+2-6, y-1-6, 2*x*x-8, z*z+4-5, y-z-8], [x, y, z])
print(a)

In [ ]:
#Bai 5
import numpy as np
A = np.reshape(np.arange(36.0),(6,6))
print(A)
16 == np.identity(6)
print(16)
A.size
print(A.size)
a = np.matrix.diagonal(A)
print(a)
A = A + 16
print(A)
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)
D = np.array([[1., 2., 3., 4., 5., 6.],[1., 0., 1., 0., 1., 0.]])
print(D)
E = A.dot(D)
print(E)
F = np.array([[1., 1.],[2., 0.],[3., 1.],[4., 0.],[5., 1.],[6., 0.]])
G = A.dot(F)
print(F)
print(G)
b = np.linalg.inv(A)
print(b)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
16
36
[ 0.  7. 14. 21. 28. 35.]
[[16. 17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33.]
 [34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45.]
 [46. 47. 48. 49. 50. 51.]]
[ 406.  532.  658.  784.  910. 1036.]
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 406.   54.]
 [ 532.   72.]
 [ 658.   90.]
 [ 784.  108.]
 [ 910.  126.]
 [1036.  144.]]


LinAlgError: Singular matrix

In [31]:
#Bai 6
import numpy as np
A = np.array([[1,1], [1,0]])
b = np.array([1, 0])
n = 10 
for i in range(n):
    b = A.dot(b)
    print(b)


[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [ ]:
#Bai 7
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)


{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


#Bai Tap Chuong

In [ ]:
#Bai tap 1
#Van de 1
import numpy as np
A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([-2, 6])
x1 = np.linalg.solve(A1, b1)
print("Van de 1:", x1)
#Van de 2
A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
b2 = np.array([2, 3, 6])
x2 = np.linalg.solve(A2, b2)
print("Van de 2:", x2)
#Van de 3
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, b3)
print("Van de 3 (a, b, c):", x3)
#Van de 4
A4 = np.array([[1, 0, 1], [1, 1, -2], [-2, 2, 1]])
b4 = np.array([1, -3, 0])
x4 = np.linalg.solve(A4, b4)
print("Van de 4 (a, b, c):", x4)


Problem 1 solution: [-4.4408921e-16  2.0000000e+00]
Problem 2 solution: [3. 1. 2.]
Problem 3 solution (a, b, c): [ 1. -4.  7.]
Problem 4 solution (a, b, c): [-0.11111111 -0.66666667  1.11111111]


In [2]:
#Bai tap 2
#Van de 1
from sympy import symbols, Eq, solve
x, y = symbols('x y')
eq1 = Eq(x - y, -2)
eq2 = Eq(2*x + 3*y, 6)
KQ1 = solve((eq1, eq2), (x, y))
print("Van de 1:", KQ1)
#Van de 2
x, y, z = symbols('x y z')
eq1 = Eq(x - y, 2)
eq2 = Eq(2*x - y - z, 3)
eq3 = Eq(x + y + z, 6)
KQ2 = solve((eq1, eq2, eq3), (x, y, z))
print("Van de 2:", KQ2)
#Van de 3
a, b, c = symbols('a b c')
eq1 = Eq(a + b + c, 4)
eq2 = Eq(4*a + 2*b + c, 3)
eq3 = Eq(9*a + 3*b + c, 4)
KQ3 = solve((eq1, eq2, eq3), (a, b, c))
print("Van de 3:", KQ3)
#Van de 4
a, b, c = symbols('a b c')
eq1 = Eq(a + c, 1)
eq2 = Eq(a + b - 2*c, -3)
eq3 = Eq(-2*a + 2*b + c, 0)
KQ4 = solve((eq1, eq2, eq3), (a, b, c))
print("Van de 4:", KQ4)





Van de 1: {x: 0, y: 2}
Van de 2: {x: 3, y: 1, z: 2}
Van de 3: {a: 1, b: -4, c: 7}
Van de 4: {a: -1/9, b: -2/3, c: 10/9}


In [ ]:
#Bai tap 3
from sympy import Matrix, pprint, symbols, Eq
from sympy.abc import k
F = Matrix([[1, 1], [1, 0]])

def luythua(n):
    return F**n
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
k_val = 5
Fk = luythua(k_val)
F_check = Matrix([
    [fib(k_val + 1), fib(k_val)],
    [fib(k_val), fib(k_val - 1)]
])
print("F^k =")
pprint(Fk)
print("\nFibonacci matrix =")
pprint(F_check)
print("\nHai ma trận bằng nhau:", Fk == F_check)


F^k =
⎡8  5⎤
⎢    ⎥
⎣5  3⎦

Fibonacci matrix =
⎡8  5⎤
⎢    ⎥
⎣5  3⎦

Hai ma trận bằng nhau? True
